# Generated by Django 5.0.6 on 2024-08-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Age', models.IntegerField(default='')),
                ('Address', models.CharField(default='', max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'datas',
            },
        ),
    ]
